package com.myeclipseide.examples.dwrspring.jpa;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Productline generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name = "PRODUCTLINE", schema = "CLASSICCARS", uniqueConstraints = {})
public class Productline implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	// Fields

	private String productline;

	private String textdescription;

	private String htmldescription;

	private String image;

	// Constructors

	public Productline() {
		/* default constructor */
	}

	/* minimal constructor */
	public Productline(String productline) {
		this.productline = productline;
	}

	/* full constructor */
	public Productline(String productline, String textdescription,
			String htmldescription, String image) {
		this.productline = productline;
		this.textdescription = textdescription;
		this.htmldescription = htmldescription;
		this.image = image;
	}

	// Property accessors
	@Id
	@Column(name = "PRODUCTLINE", unique = true, nullable = false, insertable = true, updatable = true, length = 50)
	public String getProductline() {
		return this.productline;
	}

	public void setProductline(String productline) {
		this.productline = productline;
	}

	@Column(name = "TEXTDESCRIPTION", unique = false, nullable = true, insertable = true, updatable = true, length = 4000)
	public String getTextdescription() {
		return this.textdescription;
	}

	public void setTextdescription(String textdescription) {
		this.textdescription = textdescription;
	}

	@Column(name = "HTMLDESCRIPTION", unique = false, nullable = true, insertable = true, updatable = true)
	public String getHtmldescription() {
		return this.htmldescription;
	}

	public void setHtmldescription(String htmldescription) {
		this.htmldescription = htmldescription;
	}

	@Column(name = "IMAGE", unique = false, nullable = true, insertable = true, updatable = true)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
